# shared config

management:
  endpoints:
    web:
      exposure:
        include: "*"

global:
  params:
    p1: 555
    p2: 777

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: WARN
