# shared config
eureka:
  # standalone mode
  client:
    registerWithEureka: false # Eureka server does not register itself
    fetchRegistry: false # No need to fetch registry
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  server:
    enable-self-preservation: true # Prevents services from being removed during network issues

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - loggers
          - httptrace

global:
  params:
    p1: 555
    p2: 777
