# shared config
spring:
  main:
    allow-bean-definition-overriding: true

global:
  params:
    p1: 555
    p2: 777

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - loggers
          - httptrace
