server:
  port: 8989

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-a
          uri: lb://service-a
          predicates:
            - Path=/service-a/** # Matches `/service-a/...`
        - id: service-b
          uri: lb://service-b
          predicates:
            - Path=/service-b/** # Matches `/service-b/...`
        - id: secured-service
          uri: lb://secured-service
          predicates:
            - Path=/secured-service/** # Matches `/secured-service/...`
          # no header removal — Authorization header will be forwarded by default unless you strip it

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:7080/realms/sentinel-nexus-realm
          #jwk-set-uri: http://host.docker.internal:7080/realms/sentinel-nexus-realm/protocol/openid-connect/certs
