server:
  port: 8989

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-a
          uri: lb://service-a
          predicates:
            - Path=/service-a/** # Matches `/service-a/...`
        - id: service-b
          uri: lb://service-b
          predicates:
            - Path=/service-b/** # Matches `/service-b/...`
