server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

spring:
  #  config:
  #    import: optional:configserver:http://config-server:8888/
  cloud:
    gateway:
      routes:
        - id: service_a_route
          uri: http://service-a:8081
          predicates:
            - Path=/api/service-a/**
          filters:
            - StripPrefix=2

        - id: service_b_route
          uri: http://service-b:8082
          predicates:
            - Path=/api/service-b/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
