##############################################
############## Core Services #################
##############################################
services:
  config-server:
    build: ./config-server/
    container_name: config-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-I", "http://config-server:8888"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 8888:8888
    networks:
      - sentinel_nexus_networkservices

  discovery-service:
    build: ./discovery-service/
    container_name: discovery-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-service:8761"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8761:8761
    networks:
      - sentinel_nexus_networkservices

  gateway-service:
    build: ./gateway-service/
    container_name: gateway-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - sentinel_nexus_networkservices

  service-a:
    build: ./service-a/
    container_name: service-a
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    ports:
      - 8081:8081
    networks:
      - sentinel_nexus_networkservices

  service-b:
    build: ./service-b/
    container_name: service-b
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    ports:
      - 8082:8082
    networks:
      - sentinel_nexus_networkservices

networks:
  sentinel_nexus_networkservices:
    driver: bridge
