server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abbassizied/sentinel-nexus # Location of config server
          default-label: main
          search-paths: config-repo
