server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abbassizied/sentinel-nexus/config-repo # Location of config server
          clone-on-start: true


 




